View Manager and Certain Refinements Regarding to Sell Use Case
Shaqeelhazmi/trading-API pull request #13
Opened 2023-11-19 18:13 UTC by muratb1lg1n

I've written ViewManager and created the LabelTextPanel class, which we will probably need when doing the front-end components of our project. Furthermore, I've made some improvements to SellUseCaseFactory and added "sell" method to StockDataAccessObject.

2023-11-19 18:29 UTC, Shaqeelhazmi requested changes
For the sell method in StockDataAccessObject, I do not think you manipulate the portfolio correctly. Your use case is to sell which means its supposed to subtract from the use case not add. Adding is the buy use case. Also, theres a variable named amount_used_for_purchase? I do not know how is this relevant to selling because you are not purchasing anything.

2023-11-19 19:47 UTC, muratb1lg1n commented
I've addressed the problems Shaqeel mentioned.

2023-11-19 20:03 UTC, Shaqeelhazmi approved these changes
All looks good. For future updates, you can add manipulation of transaction history in the sell method.

2023-11-20 18:28 UTC, matkuang approved these changes

2023-11-20 18:31 UTC, merged